-d C:\Users\moham\tang-nano-4k-hdmi-audio\tang_audio_demo\tang_audio_demo\impl\gwsynthesis\tang_audio_demo.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst C:\Users\moham\tang-nano-4k-hdmi-audio\tang_audio_demo\tang_audio_demo\src\hdmi.cst
-cfg C:\Users\moham\tang-nano-4k-hdmi-audio\tang_audio_demo\tang_audio_demo\impl\pnr\device.cfg
-sdc C:\Users\moham\tang-nano-4k-hdmi-audio\tang_audio_demo\tang_audio_demo\src\hdmi.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
